### ISSUE TITLE
Install problem if some of the folders have space in their name

### ISSUE THREAD

**Issue by lowzyyy** [kralverde/ravencoin-stratum-proxy#14]
Example:
I:\mining for fun\ravencoin-stratum-proxy-master\ravencoin-stratum-proxy-master\windows

CURRENT_DIRECTORY will have the correct path but when powershell execute command with:

 %CURRENT_DIRECTORY%python.zip, parser will stop at the word mining. 

In this case i had to do: 
'%CURRENT_DIRECTORY%python.zip'
And for every command with powershell i did this.

Of course not only powershell has problem with spaces. Every other path have to go under " " if they are not already under quotes

**Comment by kralverde** [comment]
I'm not really familiar with windows in general and the bat was made with abundant googling.

If you're willing, could you make a PR with this fix and anything else you see?

**Comment by kralverde** [comment]
or @Seal-Clubber could you take a look?

**Comment by Seal-Clubber** [comment]
Have seen the same happen with users that have a space in them. Work around for now would be to run the tool in C: dir or renaming your folders..

**Comment by kralverde** [comment]
nah i mean like, we just gotta quote everying. im a bit busy rn

**Comment by Seal-Clubber** [comment]
ill make a PR

**Comment by kralverde** [comment]
tyvm
