### ISSUE TITLE
Can't make it work with other kawpow coins like Neoxa/Clore

### ISSUE THREAD

**Issue by enk37** [kralverde/ravencoin-stratum-proxy#23]
Hi, i'm trying to adopt your stratum to work on other kawpow based node and getting the following rejections:
`
Error code: 20 - bad-cb-community-autonomous-amount
 `

I noticed other people are getting similar problems:

[https://www.reddit.com/r/Neoxa/comments/wd4oby/solo_mine_to_qt_wallet_with_trex_teamredminer_and/](url)

can you help to solve it please?

**Comment by enk37** [comment]
@Seal-Clubber  found your neoxa modification, but for Clore seems some other changes needed. Do you plan any?

**Comment by kralverde** [comment]
Duplicate https://github.com/kralverde/ravencoin-stratum-proxy/issues/18
